-- Name: b1; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.b1 (
    id bigint NOT NULL,
    roll_no text NOT NULL,
    student_name text NOT NULL,
    student_email text NOT NULL,
    student_password text NOT NULL,
    parent_email text,
    parent_password text
);


ALTER TABLE public.b1 OWNER TO postgres;

-- Name: b1_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.b1 ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.b1_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- Name: b2; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.b2 (
    id bigint NOT NULL,
    roll_no text NOT NULL,
    student_name text NOT NULL,
    student_email text NOT NULL,
    student_password text NOT NULL,
    parent_email text,
    parent_password text
);


ALTER TABLE public.b2 OWNER TO postgres;

-- Name: b2_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.b2 ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.b2_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- Name: b3; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.b3 (
    id bigint NOT NULL,
    roll_no text NOT NULL,
    student_name text NOT NULL,
    student_email text NOT NULL,
    student_password text NOT NULL,
    parent_email text,
    parent_password text
);


ALTER TABLE public.b3 OWNER TO postgres;

-- Name: b3_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.b3 ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.b3_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- Name: b4; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.b4 (
    id bigint NOT NULL,
    roll_no text NOT NULL,
    student_name text NOT NULL,
    student_email text NOT NULL,
    student_password text NOT NULL,
    parent_email text,
    parent_password text
);


ALTER TABLE public.b4 OWNER TO postgres;

-- Name: b4_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.b4 ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.b4_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- Name: backlogs; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.backlogs (
    id bigint NOT NULL,
    roll_no text NOT NULL,
    subject_code text NOT NULL,
    semester integer NOT NULL
);


ALTER TABLE public.backlogs OWNER TO postgres;

-- Name: backlogs_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.backlogs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.backlogs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- Name: courses; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.courses (
    course_code text NOT NULL,
    course_name text NOT NULL,
    assisting_teacher text,
    credits integer NOT NULL,
    semester integer NOT NULL
);


ALTER TABLE public.courses OWNER TO postgres;

-- Name: grades; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.grades (
    roll_no text NOT NULL,
    total_credits_sem1 integer,
    total_credits_sem2 integer,
    total_credits_sem3 integer,
    total_credits_sem4 integer,
    total_credits_sem5 integer,
    total_credits_sem6 integer,
    total_credits_sem7 integer,
    total_credits_sem8 integer,
    sgpa_sem1 numeric(4,2),
    sgpa_sem2 numeric(4,2),
    sgpa_sem3 numeric(4,2),
    sgpa_sem4 numeric(4,2),
    sgpa_sem5 numeric(4,2),
    sgpa_sem6 numeric(4,2),
    sgpa_sem7 numeric(4,2),
    sgpa_sem8 numeric(4,2),
    cgpa numeric(4,2)
);


ALTER TABLE public.grades OWNER TO postgres;

-- Name: marks1; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.marks1 (
    id bigint NOT NULL,
    roll_no text NOT NULL,
    subject_code text NOT NULL,
    credits integer,
    mid1 integer,
    mid2 integer,
    endsem integer,
    final_grade text,
    internal_marks integer
);


ALTER TABLE public.marks1 OWNER TO postgres;

-- Name: marks1_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.marks1 ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.marks1_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- Name: marks2; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.marks2 (
    id bigint NOT NULL,
    roll_no text NOT NULL,
    subject_code text NOT NULL,
    credits integer,
    mid1 integer,
    mid2 integer,
    endsem integer,
    final_grade text,
    internal_marks integer
);


ALTER TABLE public.marks2 OWNER TO postgres;

-- Name: marks2_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.marks2 ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.marks2_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- Name: marks3; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.marks3 (
    id bigint NOT NULL,
    roll_no text NOT NULL,
    subject_code text NOT NULL,
    credits integer,
    mid1 integer,
    mid2 integer,
    endsem integer,
    final_grade text,
    internal_marks integer
);


ALTER TABLE public.marks3 OWNER TO postgres;

-- Name: marks3_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.marks3 ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.marks3_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- Name: marks4; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.marks4 (
    id bigint NOT NULL,
    roll_no text NOT NULL,
    subject_code text NOT NULL,
    credits integer,
    mid1 integer,
    mid2 integer,
    endsem integer,
    final_grade text,
    internal_marks integer
);


ALTER TABLE public.marks4 OWNER TO postgres;

-- Name: marks4_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.marks4 ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.marks4_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- Name: teachers; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.teachers (
    teacher_id bigint NOT NULL,
    username text NOT NULL,
    teacher_name text NOT NULL,
    department text,
    teacher_password text NOT NULL,
    teacher_email text NOT NULL
);


ALTER TABLE public.teachers OWNER TO postgres;

-- Name: teachers_teacher_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.teachers ALTER COLUMN teacher_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.teachers_teacher_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- Name: b1_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.b1_id_seq', 1, false);

-- Name: b2_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.b2_id_seq', 1, true);

-- Name: b3_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.b3_id_seq', 1, false);

-- Name: b4_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.b4_id_seq', 1, false);

-- Name: backlogs_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.backlogs_id_seq', 1, false);

-- Name: marks1_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.marks1_id_seq', 1, false);

-- Name: marks2_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.marks2_id_seq', 1, false);

-- Name: marks3_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.marks3_id_seq', 1, false);

-- Name: marks4_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.marks4_id_seq', 1, false);

-- Name: teachers_teacher_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.teachers_teacher_id_seq', 1, false);

-- Name: b1 b1_parent_email_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.b1
    ADD CONSTRAINT b1_parent_email_key UNIQUE (parent_email);

-- Name: b1 b1_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.b1
    ADD CONSTRAINT b1_pkey PRIMARY KEY (id);

-- Name: b1 b1_roll_no_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.b1
    ADD CONSTRAINT b1_roll_no_key UNIQUE (roll_no);

-- Name: b1 b1_student_email_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.b1
    ADD CONSTRAINT b1_student_email_key UNIQUE (student_email);

-- Name: b2 b2_parent_email_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.b2
    ADD CONSTRAINT b2_parent_email_key UNIQUE (parent_email);

-- Name: b2 b2_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.b2
    ADD CONSTRAINT b2_pkey PRIMARY KEY (id);

-- Name: b2 b2_roll_no_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.b2
    ADD CONSTRAINT b2_roll_no_key UNIQUE (roll_no);

-- Name: b2 b2_student_email_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.b2
    ADD CONSTRAINT b2_student_email_key UNIQUE (student_email);

-- Name: b3 b3_parent_email_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.b3
    ADD CONSTRAINT b3_parent_email_key UNIQUE (parent_email);

-- Name: b3 b3_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.b3
    ADD CONSTRAINT b3_pkey PRIMARY KEY (id);

-- Name: b3 b3_roll_no_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.b3
    ADD CONSTRAINT b3_roll_no_key UNIQUE (roll_no);

-- Name: b3 b3_student_email_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.b3
    ADD CONSTRAINT b3_student_email_key UNIQUE (student_email);

-- Name: b4 b4_parent_email_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.b4
    ADD CONSTRAINT b4_parent_email_key UNIQUE (parent_email);

-- Name: b4 b4_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.b4
    ADD CONSTRAINT b4_pkey PRIMARY KEY (id);

-- Name: b4 b4_roll_no_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.b4
    ADD CONSTRAINT b4_roll_no_key UNIQUE (roll_no);

-- Name: b4 b4_student_email_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.b4
    ADD CONSTRAINT b4_student_email_key UNIQUE (student_email);

-- Name: backlogs backlogs_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.backlogs
    ADD CONSTRAINT backlogs_pkey PRIMARY KEY (id);

-- Name: courses courses_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.courses
    ADD CONSTRAINT courses_pkey PRIMARY KEY (course_code);

-- Name: grades grades_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.grades
    ADD CONSTRAINT grades_pkey PRIMARY KEY (roll_no);

-- Name: marks1 marks1_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.marks1
    ADD CONSTRAINT marks1_pkey PRIMARY KEY (id);

-- Name: marks2 marks2_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.marks2
    ADD CONSTRAINT marks2_pkey PRIMARY KEY (id);

-- Name: marks3 marks3_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.marks3
    ADD CONSTRAINT marks3_pkey PRIMARY KEY (id);

-- Name: marks4 marks4_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.marks4
    ADD CONSTRAINT marks4_pkey PRIMARY KEY (id);

-- Name: teachers teachers_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.teachers
    ADD CONSTRAINT teachers_pkey PRIMARY KEY (teacher_id);

-- Name: teachers teachers_teacher_email_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.teachers
    ADD CONSTRAINT teachers_teacher_email_key UNIQUE (teacher_email);

-- Name: teachers teachers_username_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.teachers
    ADD CONSTRAINT teachers_username_key UNIQUE (username);

-- Name: TABLE b1; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.b1 TO anon;
GRANT ALL ON TABLE public.b1 TO authenticated;
GRANT ALL ON TABLE public.b1 TO service_role;

-- Name: SEQUENCE b1_id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.b1_id_seq TO anon;
GRANT ALL ON SEQUENCE public.b1_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.b1_id_seq TO service_role;

-- Name: TABLE b2; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.b2 TO anon;
GRANT ALL ON TABLE public.b2 TO authenticated;
GRANT ALL ON TABLE public.b2 TO service_role;

-- Name: SEQUENCE b2_id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.b2_id_seq TO anon;
GRANT ALL ON SEQUENCE public.b2_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.b2_id_seq TO service_role;

-- Name: TABLE b3; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.b3 TO anon;
GRANT ALL ON TABLE public.b3 TO authenticated;
GRANT ALL ON TABLE public.b3 TO service_role;

-- Name: SEQUENCE b3_id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.b3_id_seq TO anon;
GRANT ALL ON SEQUENCE public.b3_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.b3_id_seq TO service_role;

-- Name: TABLE b4; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.b4 TO anon;
GRANT ALL ON TABLE public.b4 TO authenticated;
GRANT ALL ON TABLE public.b4 TO service_role;

-- Name: SEQUENCE b4_id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.b4_id_seq TO anon;
GRANT ALL ON SEQUENCE public.b4_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.b4_id_seq TO service_role;

-- Name: TABLE backlogs; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.backlogs TO anon;
GRANT ALL ON TABLE public.backlogs TO authenticated;
GRANT ALL ON TABLE public.backlogs TO service_role;

-- Name: SEQUENCE backlogs_id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.backlogs_id_seq TO anon;
GRANT ALL ON SEQUENCE public.backlogs_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.backlogs_id_seq TO service_role;

-- Name: TABLE courses; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.courses TO anon;
GRANT ALL ON TABLE public.courses TO authenticated;
GRANT ALL ON TABLE public.courses TO service_role;

-- Name: TABLE grades; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.grades TO anon;
GRANT ALL ON TABLE public.grades TO authenticated;
GRANT ALL ON TABLE public.grades TO service_role;

-- Name: TABLE marks1; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.marks1 TO anon;
GRANT ALL ON TABLE public.marks1 TO authenticated;
GRANT ALL ON TABLE public.marks1 TO service_role;

-- Name: SEQUENCE marks1_id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.marks1_id_seq TO anon;
GRANT ALL ON SEQUENCE public.marks1_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.marks1_id_seq TO service_role;

-- Name: TABLE marks2; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.marks2 TO anon;
GRANT ALL ON TABLE public.marks2 TO authenticated;
GRANT ALL ON TABLE public.marks2 TO service_role;

-- Name: SEQUENCE marks2_id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.marks2_id_seq TO anon;
GRANT ALL ON SEQUENCE public.marks2_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.marks2_id_seq TO service_role;

-- Name: TABLE marks3; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.marks3 TO anon;
GRANT ALL ON TABLE public.marks3 TO authenticated;
GRANT ALL ON TABLE public.marks3 TO service_role;

-- Name: SEQUENCE marks3_id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.marks3_id_seq TO anon;
GRANT ALL ON SEQUENCE public.marks3_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.marks3_id_seq TO service_role;

-- Name: TABLE marks4; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.marks4 TO anon;
GRANT ALL ON TABLE public.marks4 TO authenticated;
GRANT ALL ON TABLE public.marks4 TO service_role;

-- Name: SEQUENCE marks4_id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.marks4_id_seq TO anon;
GRANT ALL ON SEQUENCE public.marks4_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.marks4_id_seq TO service_role;

-- Name: TABLE teachers; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.teachers TO anon;
GRANT ALL ON TABLE public.teachers TO authenticated;
GRANT ALL ON TABLE public.teachers TO service_role;

-- Name: SEQUENCE teachers_teacher_id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.teachers_teacher_id_seq TO anon;
GRANT ALL ON SEQUENCE public.teachers_teacher_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.teachers_teacher_id_seq TO service_role;

-- Name: DEFAULT PRIVILEGES FOR SEQUENCES; Type: DEFAULT ACL; Schema: public; Owner: postgres
--

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON SEQUENCES TO postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON SEQUENCES TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON SEQUENCES TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON SEQUENCES TO service_role;

-- Name: DEFAULT PRIVILEGES FOR SEQUENCES; Type: DEFAULT ACL; Schema: public; Owner: supabase_admin
--

ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON SEQUENCES TO postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON SEQUENCES TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON SEQUENCES TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON SEQUENCES TO service_role;

-- Name: DEFAULT PRIVILEGES FOR FUNCTIONS; Type: DEFAULT ACL; Schema: public; Owner: postgres
--

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON FUNCTIONS TO postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON FUNCTIONS TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON FUNCTIONS TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON FUNCTIONS TO service_role;

-- Name: DEFAULT PRIVILEGES FOR FUNCTIONS; Type: DEFAULT ACL; Schema: public; Owner: supabase_admin
--

ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON FUNCTIONS TO postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON FUNCTIONS TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON FUNCTIONS TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON FUNCTIONS TO service_role;

-- Name: DEFAULT PRIVILEGES FOR TABLES; Type: DEFAULT ACL; Schema: public; Owner: postgres
--

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON TABLES TO postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON TABLES TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON TABLES TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON TABLES TO service_role;

-- Name: DEFAULT PRIVILEGES FOR TABLES; Type: DEFAULT ACL; Schema: public; Owner: supabase_admin
--

ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON TABLES TO postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON TABLES TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON TABLES TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON TABLES TO service_role;
