-- Hostel & Warden Management System Schema

-- 1. Hostels Table
CREATE TABLE IF NOT EXISTS "hostels" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" TEXT UNIQUE NOT NULL, -- BH1, BH2, GH1, etc.
    "capacity" INTEGER DEFAULT 100,
    "description" TEXT
);

-- Seed basic hostels
INSERT INTO "hostels" ("name") VALUES 
('BH1'), ('BH2'), ('BH3'), 
('GH1'), ('GH2'), 
('OH1'), ('OH2')
ON CONFLICT ("name") DO NOTHING;

-- 2. Wardens Table (Links teachers to hostels)
CREATE TABLE IF NOT EXISTS "wardens" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "teacher_email" TEXT NOT NULL,
    "hostel_name" TEXT NOT NULL REFERENCES "hostels"("name"),
    "assigned_at" TIMESTAMPTZ DEFAULT now(),
    UNIQUE("hostel_name") -- One warden per hostel
);

-- 3. Student Hostel Assignments
CREATE TABLE IF NOT EXISTS "hostel_assignments" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "roll_no" TEXT NOT NULL UNIQUE,
    "hostel_name" TEXT NOT NULL REFERENCES "hostels"("name"),
    "room_no" TEXT NOT NULL,
    "assigned_at" TIMESTAMPTZ DEFAULT now()
);

-- 4. Hostel Complaints
CREATE TABLE IF NOT EXISTS "hostel_complaints" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "roll_no" TEXT NOT NULL,
    "hostel_name" TEXT NOT NULL,
    "message" TEXT NOT NULL,
    "status" TEXT DEFAULT 'pending', -- pending, seen, resolved
    "admin_remarks" TEXT,
    "created_at" TIMESTAMPTZ DEFAULT now()
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_hostel_assign_roll ON "hostel_assignments"("roll_no");
CREATE INDEX IF NOT EXISTS idx_hostel_assign_name ON "hostel_assignments"("hostel_name");
CREATE INDEX IF NOT EXISTS idx_complaints_roll ON "hostel_complaints"("roll_no");
CREATE INDEX IF NOT EXISTS idx_complaints_hostel ON "hostel_complaints"("hostel_name");
