-- 1. Create the Alumni table (same schema as b1-b4)
CREATE TABLE IF NOT EXISTS "alumni" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "roll_no" TEXT UNIQUE NOT NULL,
    "student_name" TEXT NOT NULL,
    "student_email" TEXT UNIQUE NOT NULL,
    "student_password" TEXT NOT NULL,
    "parent_email" TEXT UNIQUE,
    "parent_password" TEXT,
    "parent_phone_number" TEXT,
    "department" TEXT
);

-- 2. Create promotion_log table to track promotion events
CREATE TABLE IF NOT EXISTS "promotion_log" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "promoted_by" TEXT NOT NULL,
    "promoted_at" TIMESTAMPTZ DEFAULT now(),
    "academic_year" TEXT,
    "students_promoted" INTEGER DEFAULT 0,
    "students_to_alumni" INTEGER DEFAULT 0,
    "year_back_excluded" INTEGER DEFAULT 0,
    "notes" TEXT
);

-- 3. Create year_back_students table
CREATE TABLE IF NOT EXISTS "year_back_students" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "roll_no" TEXT NOT NULL,
    "student_name" TEXT,
    "current_batch" TEXT NOT NULL,
    "reason" TEXT,
    "created_at" TIMESTAMPTZ DEFAULT now(),
    UNIQUE("roll_no", "current_batch")
);

-- 4. Recreate backlogs table (Drops existing to ensure new schema)
DROP TABLE IF EXISTS "backlogs" CASCADE;

CREATE TABLE "backlogs" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "roll_no" TEXT NOT NULL,
    "subject_code" TEXT NOT NULL,
    "subject_name" TEXT,
    "batch_when_failed" TEXT,
    "semester" INTEGER,
    "status" TEXT DEFAULT 'active',
    "cleared_date" TIMESTAMPTZ,
    "created_at" TIMESTAMPTZ DEFAULT now()
);

-- 5. Drop FK constraints on attendance tables so records survive promotion
-- (attendance records are historical and should NOT be cascade-deleted)
ALTER TABLE attendance1 DROP CONSTRAINT IF EXISTS fk_student_b1;
ALTER TABLE attendance2 DROP CONSTRAINT IF EXISTS fk_student_b2;
ALTER TABLE attendance3 DROP CONSTRAINT IF EXISTS fk_student_b3;
ALTER TABLE attendance4 DROP CONSTRAINT IF EXISTS fk_student_b4;

-- 6. Create indexes for performance
CREATE INDEX IF NOT EXISTS idx_alumni_roll_no ON "alumni"("roll_no");
CREATE INDEX IF NOT EXISTS idx_year_back_roll_no ON "year_back_students"("roll_no");
CREATE INDEX IF NOT EXISTS idx_year_back_batch ON "year_back_students"("current_batch");
CREATE INDEX IF NOT EXISTS idx_backlogs_status ON "backlogs"("status");
CREATE INDEX IF NOT EXISTS idx_backlogs_roll_no ON "backlogs"("roll_no");
CREATE INDEX IF NOT EXISTS idx_promotion_log_date ON "promotion_log"("promoted_at");

-- 7. Result Announcement Management
CREATE TABLE IF NOT EXISTS "result_announcements" (
    "batch" TEXT PRIMARY KEY,
    "mid1_announced" BOOLEAN DEFAULT false,
    "mid2_announced" BOOLEAN DEFAULT false,
    "endsem_announced" BOOLEAN DEFAULT false,
    "current_sem_type" TEXT DEFAULT 'odd', -- 'odd' or 'even'
    "updated_at" TIMESTAMPTZ DEFAULT now()
);

INSERT INTO "result_announcements" ("batch") 
VALUES ('b1'), ('b2'), ('b3'), ('b4')
ON CONFLICT ("batch") DO NOTHING;
-- 8. Even Semester Marks Tables (marks1e, marks2e, marks3e, marks4e)
CREATE TABLE IF NOT EXISTS "marks1e" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "roll_no" TEXT NOT NULL,
    "subject_code" TEXT NOT NULL,
    "internal_marks" NUMERIC(5, 2),
    "mid1" NUMERIC(5, 2),
    "mid2" NUMERIC(5, 2),
    "endsem" NUMERIC(5, 2),
    "credits" INTEGER DEFAULT 4,
    "updated_at" TIMESTAMPTZ DEFAULT now(),
    UNIQUE("roll_no", "subject_code")
);

CREATE TABLE IF NOT EXISTS "marks2e" (LIKE "marks1e" INCLUDING ALL);
CREATE TABLE IF NOT EXISTS "marks3e" (LIKE "marks1e" INCLUDING ALL);
CREATE TABLE IF NOT EXISTS "marks4e" (LIKE "marks1e" INCLUDING ALL);