-- Copy and run this script in the Supabase SQL Editor

-- 1. Add 'department' to student tables (to allow filtering by department)
ALTER TABLE b1 ADD COLUMN IF NOT EXISTS department TEXT;
ALTER TABLE b2 ADD COLUMN IF NOT EXISTS department TEXT;
ALTER TABLE b3 ADD COLUMN IF NOT EXISTS department TEXT;
ALTER TABLE b4 ADD COLUMN IF NOT EXISTS department TEXT;

-- 2. Create the Notifications table
CREATE TABLE IF NOT EXISTS notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sender_username TEXT NOT NULL,
    sender_name TEXT,
    message TEXT NOT NULL,
    target_batch TEXT, -- e.g., 'b1', 'b2', 'b3', 'b4', or 'ALL'
    target_department TEXT, -- e.g., 'Computer Science', 'Mathematics', or 'ALL'
    created_at TIMESTAMPTZ DEFAULT now()
);

-- 3. Create the Notification Reads table (tracks which student read which notification)
CREATE TABLE IF NOT EXISTS notification_reads (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    notification_id BIGINT REFERENCES notifications(id) ON DELETE CASCADE,
    roll_no TEXT NOT NULL,
    read_at TIMESTAMPTZ DEFAULT now(),
    UNIQUE(notification_id, roll_no) -- Ensures a student can only read a notification once
);

-- Optional: Create an index for faster lookups when grabbing unread notifications
CREATE INDEX IF NOT EXISTS idx_notifications_targets ON notifications(target_batch, target_department);
CREATE INDEX IF NOT EXISTS idx_notification_reads_roll_no ON notification_reads(roll_no);
